/**
 * Scientific constants and unit conversions for the Math Solver.
 * Architecture is expandable: add new categories or units freely.
 */

export interface ScientificConstant {
  symbol: string;
  name: string;
  value: number;
  unit: string;
  category: "math" | "physics" | "chemistry" | "astronomy" | "universal";
}

// NaN is used for non-numeric constants (like i)
const NAN = NaN;

export const SCIENTIFIC_CONSTANTS: ScientificConstant[] = [
  // === Mathematical ===
  { symbol: "π", name: "Pi", value: Math.PI, unit: "", category: "math" },
  { symbol: "e", name: "Euler's number", value: Math.E, unit: "", category: "math" },
  { symbol: "φ", name: "Golden ratio", value: (1 + Math.sqrt(5)) / 2, unit: "", category: "math" },
  { symbol: "√2", name: "Pythagoras constant", value: Math.SQRT2, unit: "", category: "math" },
  { symbol: "√3", name: "Theodorus constant", value: Math.sqrt(3), unit: "", category: "math" },
  { symbol: "ln(2)", name: "Natural log of 2", value: Math.LN2, unit: "", category: "math" },
  { symbol: "ln(10)", name: "Natural log of 10", value: Math.LN10, unit: "", category: "math" },
  { symbol: "log₂(e)", name: "Log base 2 of e", value: Math.LOG2E, unit: "", category: "math" },
  { symbol: "log₁₀(e)", name: "Log base 10 of e", value: Math.LOG10E, unit: "", category: "math" },
  { symbol: "γ", name: "Euler-Mascheroni constant", value: 0.5772156649, unit: "", category: "math" },
  { symbol: "i", name: "Imaginary unit", value: NAN, unit: "", category: "math" },
  { symbol: "∞", name: "Infinity", value: Infinity, unit: "", category: "math" },

  // === Universal / Fundamental ===
  { symbol: "c", name: "Speed of light in vacuum", value: 299792458, unit: "m/s", category: "universal" },
  { symbol: "G", name: "Gravitational constant", value: 6.6743e-11, unit: "N·m²/kg²", category: "universal" },
  { symbol: "h", name: "Planck constant", value: 6.62607015e-34, unit: "J·s", category: "universal" },
  { symbol: "ħ", name: "Reduced Planck constant (h/2π)", value: 1.054571817e-34, unit: "J·s", category: "universal" },
  { symbol: "k_B", name: "Boltzmann constant", value: 1.380649e-23, unit: "J/K", category: "universal" },
  { symbol: "N_A", name: "Avogadro constant", value: 6.02214076e23, unit: "mol⁻¹", category: "universal" },

  // === Physics — Mechanics ===
  { symbol: "g", name: "Acceleration due to gravity (Earth)", value: 9.80665, unit: "m/s²", category: "physics" },
  { symbol: "gₘ", name: "Gravity on Mars", value: 3.71, unit: "m/s²", category: "physics" },
  { symbol: "gₘₒₒₙ", name: "Gravity on Moon", value: 1.62, unit: "m/s²", category: "physics" },
  { symbol: "g☉", name: "Gravity on Sun", value: 274, unit: "m/s²", category: "physics" },
  { symbol: "g♃", name: "Gravity on Jupiter", value: 24.79, unit: "m/s²", category: "physics" },
  { symbol: "R_E", name: "Radius of Earth", value: 6.371e6, unit: "m", category: "physics" },
  { symbol: "M_E", name: "Mass of Earth", value: 5.972e24, unit: "kg", category: "physics" },
  { symbol: "R_M", name: "Radius of Moon", value: 1.737e6, unit: "m", category: "physics" },
  { symbol: "M_M", name: "Mass of Moon", value: 7.342e22, unit: "kg", category: "physics" },
  { symbol: "v_esc", name: "Escape velocity (Earth)", value: 11.2, unit: "km/s", category: "physics" },
  { symbol: "v_orb", name: "Orbital velocity (Earth)", value: 7.9, unit: "km/s", category: "physics" },

  // === Physics — Electromagnetic ===
  { symbol: "e", name: "Elementary charge", value: 1.602176634e-19, unit: "C", category: "physics" },
  { symbol: "eV", name: "Electron volt", value: 1.602176634e-19, unit: "J", category: "physics" },
  { symbol: "ε₀", name: "Permittivity of free space", value: 8.854187817e-12, unit: "F/m or C²/(N·m²)", category: "physics" },
  { symbol: "μ₀", name: "Permeability of free space", value: 4 * Math.PI * 1e-7, unit: "T·m/A or H/m", category: "physics" },
  { symbol: "k", name: "Coulomb constant (1/4πε₀)", value: 8.9875517923e9, unit: "N·m²/C²", category: "physics" },
  { symbol: "Z₀", name: "Impedance of free space", value: 376.730313668, unit: "Ω", category: "physics" },
  { symbol: "α", name: "Fine-structure constant", value: 7.2973525693e-3, unit: "", category: "physics" },
  { symbol: "Φ₀", name: "Magnetic flux quantum", value: 2.067833848e-15, unit: "Wb", category: "physics" },
  { symbol: "G_F", name: "Fermi coupling constant", value: 1.1663787e-5, unit: "GeV⁻²", category: "physics" },

  // === Physics — Thermodynamic ===
  { symbol: "σ", name: "Stefan-Boltzmann constant", value: 5.670374419e-8, unit: "W/(m²·K⁴)", category: "physics" },
  { symbol: "R", name: "Universal gas constant", value: 8.314462618, unit: "J/(mol·K)", category: "physics" },
  { symbol: "F", name: "Faraday constant", value: 96485.33212, unit: "C/mol", category: "physics" },
  { symbol: "c₁", name: "First radiation constant", value: 3.741771852e-16, unit: "W·m²", category: "physics" },
  { symbol: "c₂", name: "Second radiation constant", value: 1.438776877e-2, unit: "m·K", category: "physics" },
  { symbol: "b", name: "Wien's displacement constant", value: 2.897771955e-3, unit: "m·K", category: "physics" },
  { symbol: "T₀", name: "Triple point of water", value: 273.16, unit: "K", category: "physics" },
  { symbol: "T_STP", name: "Standard temperature (STP)", value: 273.15, unit: "K", category: "physics" },
  { symbol: "P_STP", name: "Standard pressure (STP)", value: 101325, unit: "Pa", category: "physics" },
  { symbol: "L_f", name: "Latent heat of fusion (water)", value: 3.33e5, unit: "J/kg", category: "physics" },
  { symbol: "L_v", name: "Latent heat of vaporization (water)", value: 2.26e6, unit: "J/kg", category: "physics" },
  { symbol: "c_water", name: "Specific heat capacity (water)", value: 4186, unit: "J/(kg·K)", category: "physics" },
  { symbol: "c_ice", name: "Specific heat capacity (ice)", value: 2090, unit: "J/(kg·K)", category: "physics" },
  { symbol: "c_steam", name: "Specific heat capacity (steam)", value: 2010, unit: "J/(kg·K)", category: "physics" },
  { symbol: "c_cu", name: "Specific heat (copper)", value: 385, unit: "J/(kg·K)", category: "physics" },
  { symbol: "c_Al", name: "Specific heat (aluminium)", value: 900, unit: "J/(kg·K)", category: "physics" },
  { symbol: "c_Fe", name: "Specific heat (iron)", value: 450, unit: "J/(kg·K)", category: "physics" },
  { symbol: "c_Ag", name: "Specific heat (silver)", value: 235, unit: "J/(kg·K)", category: "physics" },
  { symbol: "c_Pb", name: "Specific heat (lead)", value: 128, unit: "J/(kg·K)", category: "physics" },
  { symbol: "c_Hg", name: "Specific heat (mercury)", value: 139, unit: "J/(kg·K)", category: "physics" },
  { symbol: "ρ_Hg", name: "Density of mercury", value: 13600, unit: "kg/m³", category: "physics" },
  { symbol: "ρ_water", name: "Density of water (4°C)", value: 1000, unit: "kg/m³", category: "physics" },
  { symbol: "ρ_ice", name: "Density of ice", value: 917, unit: "kg/m³", category: "physics" },
  { symbol: "ρ_air", name: "Density of air (STP)", value: 1.293, unit: "kg/m³", category: "physics" },
  { symbol: "ρ_Au", name: "Density of gold", value: 19300, unit: "kg/m³", category: "physics" },
  { symbol: "ρ_Ag", name: "Density of silver", value: 10500, unit: "kg/m³", category: "physics" },
  { symbol: "ρ_Cu", name: "Density of copper", value: 8960, unit: "kg/m³", category: "physics" },
  { symbol: "ρ_Fe", name: "Density of iron", value: 7870, unit: "kg/m³", category: "physics" },
  { symbol: "ρ_Al", name: "Density of aluminium", value: 2700, unit: "kg/m³", category: "physics" },
  { symbol: "γ_water", name: "Surface tension (water)", value: 0.0728, unit: "N/m", category: "physics" },
  { symbol: "η_water", name: "Viscosity of water (20°C)", value: 1.002e-3, unit: "Pa·s", category: "physics" },
  { symbol: "η_air", name: "Viscosity of air (20°C)", value: 1.81e-5, unit: "Pa·s", category: "physics" },

  // === Physics — Particle masses ===
  { symbol: "m_e", name: "Electron mass", value: 9.1093837e-31, unit: "kg", category: "physics" },
  { symbol: "m_p", name: "Proton mass", value: 1.6726219e-27, unit: "kg", category: "physics" },
  { symbol: "m_n", name: "Neutron mass", value: 1.6749275e-27, unit: "kg", category: "physics" },
  { symbol: "m_μ", name: "Muon mass", value: 1.883531627e-28, unit: "kg", category: "physics" },
  { symbol: "m_τ", name: "Tau mass", value: 3.16754e-27, unit: "kg", category: "physics" },
  { symbol: "m_α", name: "Alpha particle mass", value: 6.6446573357e-27, unit: "kg", category: "physics" },
  { symbol: "m_e(u)", name: "Electron mass (u)", value: 0.00054858, unit: "u", category: "physics" },
  { symbol: "m_p(u)", name: "Proton mass (u)", value: 1.007276, unit: "u", category: "physics" },
  { symbol: "m_n(u)", name: "Neutron mass (u)", value: 1.008665, unit: "u", category: "physics" },
  { symbol: "m_e(MeV)", name: "Electron rest energy", value: 0.510999, unit: "MeV", category: "physics" },
  { symbol: "m_p(MeV)", name: "Proton rest energy", value: 938.272, unit: "MeV", category: "physics" },
  { symbol: "m_n(MeV)", name: "Neutron rest energy", value: 939.565, unit: "MeV", category: "physics" },

  // === Physics — Atomic ===
  { symbol: "a₀", name: "Bohr radius", value: 5.29177210903e-11, unit: "m", category: "physics" },
  { symbol: "E_h", name: "Hartree energy", value: 4.3597447222071e-18, unit: "J", category: "physics" },
  { symbol: "R∞", name: "Rydberg constant", value: 10973731.568160, unit: "m⁻¹", category: "physics" },
  { symbol: "R_H", name: "Rydberg constant (hydrogen)", value: 10967700, unit: "m⁻¹", category: "physics" },
  { symbol: "R∞(hc)", name: "Rydberg energy (R∞·h·c)", value: 13.605693, unit: "eV", category: "physics" },
  { symbol: "r_e", name: "Classical electron radius", value: 2.8179403262e-15, unit: "m", category: "physics" },
  { symbol: "λ_C", name: "Compton wavelength (electron)", value: 2.4263102367e-12, unit: "m", category: "physics" },
  { symbol: "μ_B", name: "Bohr magneton", value: 9.2740100783e-24, unit: "J/T", category: "physics" },
  { symbol: "μ_N", name: "Nuclear magneton", value: 5.0507837461e-27, unit: "J/T", category: "physics" },
  { symbol: "e/m_e", name: "Specific charge of electron", value: 1.758820e11, unit: "C/kg", category: "physics" },

  // === Physics — Quantum ===
  { symbol: "ℓ_P", name: "Planck length", value: 1.616255e-35, unit: "m", category: "physics" },
  { symbol: "t_P", name: "Planck time", value: 5.391247e-44, unit: "s", category: "physics" },
  { symbol: "m_P", name: "Planck mass", value: 2.176434e-8, unit: "kg", category: "physics" },
  { symbol: "T_P", name: "Planck temperature", value: 1.416784e32, unit: "K", category: "physics" },
  { symbol: "E_P", name: "Planck energy", value: 1.956e9, unit: "J", category: "physics" },

  // === Physics — Sound & Waves ===
  { symbol: "v_sound", name: "Speed of sound (air, 0°C)", value: 331, unit: "m/s", category: "physics" },
  { symbol: "v_sound20", name: "Speed of sound (air, 20°C)", value: 343, unit: "m/s", category: "physics" },
  { symbol: "v_sound_H₂O", name: "Speed of sound (water)", value: 1482, unit: "m/s", category: "physics" },
  { symbol: "v_sound_steel", name: "Speed of sound (steel)", value: 5960, unit: "m/s", category: "physics" },

  // === Physics — Optical ===
  { symbol: "n_air", name: "Refractive index (air)", value: 1.0003, unit: "", category: "physics" },
  { symbol: "n_water", name: "Refractive index (water)", value: 1.33, unit: "", category: "physics" },
  { symbol: "n_glass", name: "Refractive index (glass)", value: 1.5, unit: "", category: "physics" },
  { symbol: "n_diamond", name: "Refractive index (diamond)", value: 2.42, unit: "", category: "physics" },
  { symbol: "n_quartz", name: "Refractive index (quartz)", value: 1.46, unit: "", category: "physics" },

  // === Chemistry — Fundamental ===
  { symbol: "N_A", name: "Avogadro number", value: 6.02214076e23, unit: "mol⁻¹", category: "chemistry" },
  { symbol: "R", name: "Molar gas constant", value: 8.314462618, unit: "J/(mol·K)", category: "chemistry" },
  { symbol: "F", name: "Faraday constant", value: 96485.33212, unit: "C/mol", category: "chemistry" },
  { symbol: "k_B", name: "Boltzmann constant", value: 1.380649e-23, unit: "J/K", category: "chemistry" },
  { symbol: "V_m", name: "Molar volume at STP", value: 22.414, unit: "L/mol", category: "chemistry" },
  { symbol: "V_m(STP)", name: "Molar volume at STP (m³)", value: 0.022414, unit: "m³/mol", category: "chemistry" },
  { symbol: "pK_w", name: "Water ionization constant (pKw, 25°C)", value: 14.0, unit: "", category: "chemistry" },
  { symbol: "K_w", name: "Ion product of water (25°C)", value: 1.0e-14, unit: "mol²/L²", category: "chemistry" },
  { symbol: "pH", name: "Neutral pH (at 25°C)", value: 7.0, unit: "", category: "chemistry" },
  { symbol: "u", name: "Unified atomic mass unit", value: 1.66053906660e-27, unit: "kg", category: "chemistry" },
  { symbol: "u(MeV)", name: "Atomic mass unit (energy)", value: 931.494, unit: "MeV/c²", category: "chemistry" },

  // === Chemistry — Atomic masses of common elements (NCERT) ===
  { symbol: "H", name: "Atomic mass of Hydrogen", value: 1.008, unit: "u", category: "chemistry" },
  { symbol: "He", name: "Atomic mass of Helium", value: 4.003, unit: "u", category: "chemistry" },
  { symbol: "Li", name: "Atomic mass of Lithium", value: 6.941, unit: "u", category: "chemistry" },
  { symbol: "Be", name: "Atomic mass of Beryllium", value: 9.012, unit: "u", category: "chemistry" },
  { symbol: "B", name: "Atomic mass of Boron", value: 10.811, unit: "u", category: "chemistry" },
  { symbol: "C", name: "Atomic mass of Carbon", value: 12.011, unit: "u", category: "chemistry" },
  { symbol: "N", name: "Atomic mass of Nitrogen", value: 14.007, unit: "u", category: "chemistry" },
  { symbol: "O", name: "Atomic mass of Oxygen", value: 15.999, unit: "u", category: "chemistry" },
  { symbol: "F", name: "Atomic mass of Fluorine", value: 18.998, unit: "u", category: "chemistry" },
  { symbol: "Ne", name: "Atomic mass of Neon", value: 20.180, unit: "u", category: "chemistry" },
  { symbol: "Na", name: "Atomic mass of Sodium", value: 22.990, unit: "u", category: "chemistry" },
  { symbol: "Mg", name: "Atomic mass of Magnesium", value: 24.305, unit: "u", category: "chemistry" },
  { symbol: "Al", name: "Atomic mass of Aluminium", value: 26.982, unit: "u", category: "chemistry" },
  { symbol: "Si", name: "Atomic mass of Silicon", value: 28.086, unit: "u", category: "chemistry" },
  { symbol: "P", name: "Atomic mass of Phosphorus", value: 30.974, unit: "u", category: "chemistry" },
  { symbol: "S", name: "Atomic mass of Sulfur", value: 32.065, unit: "u", category: "chemistry" },
  { symbol: "Cl", name: "Atomic mass of Chlorine", value: 35.45, unit: "u", category: "chemistry" },
  { symbol: "Ar", name: "Atomic mass of Argon", value: 39.948, unit: "u", category: "chemistry" },
  { symbol: "K", name: "Atomic mass of Potassium", value: 39.098, unit: "u", category: "chemistry" },
  { symbol: "Ca", name: "Atomic mass of Calcium", value: 40.078, unit: "u", category: "chemistry" },
  { symbol: "Sc", name: "Atomic mass of Scandium", value: 44.956, unit: "u", category: "chemistry" },
  { symbol: "Ti", name: "Atomic mass of Titanium", value: 47.867, unit: "u", category: "chemistry" },
  { symbol: "V", name: "Atomic mass of Vanadium", value: 50.942, unit: "u", category: "chemistry" },
  { symbol: "Cr", name: "Atomic mass of Chromium", value: 51.996, unit: "u", category: "chemistry" },
  { symbol: "Mn", name: "Atomic mass of Manganese", value: 54.938, unit: "u", category: "chemistry" },
  { symbol: "Fe", name: "Atomic mass of Iron", value: 55.845, unit: "u", category: "chemistry" },
  { symbol: "Co", name: "Atomic mass of Cobalt", value: 58.933, unit: "u", category: "chemistry" },
  { symbol: "Ni", name: "Atomic mass of Nickel", value: 58.693, unit: "u", category: "chemistry" },
  { symbol: "Cu", name: "Atomic mass of Copper", value: 63.546, unit: "u", category: "chemistry" },
  { symbol: "Zn", name: "Atomic mass of Zinc", value: 65.38, unit: "u", category: "chemistry" },
  { symbol: "Ga", name: "Atomic mass of Gallium", value: 69.723, unit: "u", category: "chemistry" },
  { symbol: "Ge", name: "Atomic mass of Germanium", value: 72.64, unit: "u", category: "chemistry" },
  { symbol: "As", name: "Atomic mass of Arsenic", value: 74.922, unit: "u", category: "chemistry" },
  { symbol: "Se", name: "Atomic mass of Selenium", value: 78.96, unit: "u", category: "chemistry" },
  { symbol: "Br", name: "Atomic mass of Bromine", value: 79.904, unit: "u", category: "chemistry" },
  { symbol: "Kr", name: "Atomic mass of Krypton", value: 83.798, unit: "u", category: "chemistry" },
  { symbol: "Rb", name: "Atomic mass of Rubidium", value: 85.468, unit: "u", category: "chemistry" },
  { symbol: "Sr", name: "Atomic mass of Strontium", value: 87.62, unit: "u", category: "chemistry" },
  { symbol: "Ag", name: "Atomic mass of Silver", value: 107.868, unit: "u", category: "chemistry" },
  { symbol: "Cd", name: "Atomic mass of Cadmium", value: 112.411, unit: "u", category: "chemistry" },
  { symbol: "Sn", name: "Atomic mass of Tin", value: 118.71, unit: "u", category: "chemistry" },
  { symbol: "I", name: "Atomic mass of Iodine", value: 126.904, unit: "u", category: "chemistry" },
  { symbol: "Xe", name: "Atomic mass of Xenon", value: 131.293, unit: "u", category: "chemistry" },
  { symbol: "Cs", name: "Atomic mass of Caesium", value: 132.905, unit: "u", category: "chemistry" },
  { symbol: "Ba", name: "Atomic mass of Barium", value: 137.327, unit: "u", category: "chemistry" },
  { symbol: "W", name: "Atomic mass of Tungsten", value: 183.84, unit: "u", category: "chemistry" },
  { symbol: "Pt", name: "Atomic mass of Platinum", value: 195.084, unit: "u", category: "chemistry" },
  { symbol: "Au", name: "Atomic mass of Gold", value: 196.967, unit: "u", category: "chemistry" },
  { symbol: "Hg", name: "Atomic mass of Mercury", value: 200.59, unit: "u", category: "chemistry" },
  { symbol: "Tl", name: "Atomic mass of Thallium", value: 204.383, unit: "u", category: "chemistry" },
  { symbol: "Pb", name: "Atomic mass of Lead", value: 207.2, unit: "u", category: "chemistry" },
  { symbol: "Bi", name: "Atomic mass of Bismuth", value: 208.980, unit: "u", category: "chemistry" },
  { symbol: "Rn", name: "Atomic mass of Radon", value: 222.018, unit: "u", category: "chemistry" },
  { symbol: "Ra", name: "Atomic mass of Radium", value: 226.025, unit: "u", category: "chemistry" },
  { symbol: "U", name: "Atomic mass of Uranium", value: 238.029, unit: "u", category: "chemistry" },
  { symbol: "Pu", name: "Atomic mass of Plutonium", value: 244.064, unit: "u", category: "chemistry" },

  // === Chemistry — Molar masses of common compounds (NCERT) ===
  { symbol: "M(H₂O)", name: "Molar mass of Water", value: 18.015, unit: "g/mol", category: "chemistry" },
  { symbol: "M(H₂)", name: "Molar mass of Hydrogen gas", value: 2.016, unit: "g/mol", category: "chemistry" },
  { symbol: "M(O₂)", name: "Molar mass of Oxygen gas", value: 31.998, unit: "g/mol", category: "chemistry" },
  { symbol: "M(N₂)", name: "Molar mass of Nitrogen gas", value: 28.014, unit: "g/mol", category: "chemistry" },
  { symbol: "M(CO₂)", name: "Molar mass of Carbon dioxide", value: 44.01, unit: "g/mol", category: "chemistry" },
  { symbol: "M(CO)", name: "Molar mass of Carbon monoxide", value: 28.01, unit: "g/mol", category: "chemistry" },
  { symbol: "M(NaCl)", name: "Molar mass of Sodium chloride", value: 58.44, unit: "g/mol", category: "chemistry" },
  { symbol: "M(HCl)", name: "Molar mass of Hydrochloric acid", value: 36.458, unit: "g/mol", category: "chemistry" },
  { symbol: "M(H₂SO₄)", name: "Molar mass of Sulfuric acid", value: 98.079, unit: "g/mol", category: "chemistry" },
  { symbol: "M(HNO₃)", name: "Molar mass of Nitric acid", value: 63.01, unit: "g/mol", category: "chemistry" },
  { symbol: "M(NaOH)", name: "Molar mass of Sodium hydroxide", value: 39.997, unit: "g/mol", category: "chemistry" },
  { symbol: "M(KOH)", name: "Molar mass of Potassium hydroxide", value: 56.106, unit: "g/mol", category: "chemistry" },
  { symbol: "M(NH₃)", name: "Molar mass of Ammonia", value: 17.031, unit: "g/mol", category: "chemistry" },
  { symbol: "M(CH₄)", name: "Molar mass of Methane", value: 16.043, unit: "g/mol", category: "chemistry" },
  { symbol: "M(C₂H₆)", name: "Molar mass of Ethane", value: 30.07, unit: "g/mol", category: "chemistry" },
  { symbol: "M(C₂H₄)", name: "Molar mass of Ethene", value: 28.054, unit: "g/mol", category: "chemistry" },
  { symbol: "M(C₂H₂)", name: "Molar mass of Ethyne", value: 26.038, unit: "g/mol", category: "chemistry" },
  { symbol: "M(C₆H₆)", name: "Molar mass of Benzene", value: 78.114, unit: "g/mol", category: "chemistry" },
  { symbol: "M(C₂H₅OH)", name: "Molar mass of Ethanol", value: 46.069, unit: "g/mol", category: "chemistry" },
  { symbol: "M(CH₃COOH)", name: "Molar mass of Acetic acid", value: 60.052, unit: "g/mol", category: "chemistry" },
  { symbol: "M(CaCO₃)", name: "Molar mass of Calcium carbonate", value: 100.087, unit: "g/mol", category: "chemistry" },
  { symbol: "M(CaO)", name: "Molar mass of Calcium oxide", value: 56.077, unit: "g/mol", category: "chemistry" },
  { symbol: "M(Ca(OH)₂)", name: "Molar mass of Calcium hydroxide", value: 74.093, unit: "g/mol", category: "chemistry" },
  { symbol: "M(KMnO₄)", name: "Molar mass of Potassium permanganate", value: 158.034, unit: "g/mol", category: "chemistry" },
  { symbol: "M(K₂Cr₂O₇)", name: "Molar mass of Potassium dichromate", value: 294.185, unit: "g/mol", category: "chemistry" },
  { symbol: "M(AgNO₃)", name: "Molar mass of Silver nitrate", value: 169.873, unit: "g/mol", category: "chemistry" },
  { symbol: "M(CuSO₄)", name: "Molar mass of Copper sulfate", value: 159.609, unit: "g/mol", category: "chemistry" },
  { symbol: "M(FeSO₄)", name: "Molar mass of Iron(II) sulfate", value: 151.908, unit: "g/mol", category: "chemistry" },
  { symbol: "M(NH₄Cl)", name: "Molar mass of Ammonium chloride", value: 53.492, unit: "g/mol", category: "chemistry" },
  { symbol: "M(Na₂CO₃)", name: "Molar mass of Sodium carbonate", value: 105.989, unit: "g/mol", category: "chemistry" },
  { symbol: "M(NaHCO₃)", name: "Molar mass of Sodium bicarbonate", value: 84.007, unit: "g/mol", category: "chemistry" },

  // === Chemistry — Equilibrium & Acid-Base ===
  { symbol: "K_a(HAc)", name: "Dissociation constant (acetic acid)", value: 1.85e-5, unit: "", category: "chemistry" },
  { symbol: "K_a(HCN)", name: "Dissociation constant (HCN)", value: 4.9e-10, unit: "", category: "chemistry" },
  { symbol: "K_a(HF)", name: "Dissociation constant (HF)", value: 6.8e-4, unit: "", category: "chemistry" },
  { symbol: "K_a(HNO₂)", name: "Dissociation constant (HNO₂)", value: 4.5e-4, unit: "", category: "chemistry" },
  { symbol: "K_a(H₂CO₃)", name: "Dissociation const. (carbonic acid, Ka1)", value: 4.3e-7, unit: "", category: "chemistry" },
  { symbol: "K_a(H₂S)", name: "Dissociation const. (hydrogen sulfide, Ka1)", value: 1.0e-7, unit: "", category: "chemistry" },
  { symbol: "K_a(H₃PO₄)", name: "Dissociation const. (phosphoric acid, Ka1)", value: 7.5e-3, unit: "", category: "chemistry" },
  { symbol: "K_b(NH₃)", name: "Dissociation constant (ammonia)", value: 1.77e-5, unit: "", category: "chemistry" },
  { symbol: "K_sp(AgCl)", name: "Solubility product (AgCl)", value: 1.8e-10, unit: "", category: "chemistry" },
  { symbol: "K_sp(BaSO₄)", name: "Solubility product (BaSO₄)", value: 1.1e-10, unit: "", category: "chemistry" },
  { symbol: "K_sp(CaCO₃)", name: "Solubility product (CaCO₃)", value: 3.3e-9, unit: "", category: "chemistry" },
  { symbol: "K_sp(CaF₂)", name: "Solubility product (CaF₂)", value: 3.9e-11, unit: "", category: "chemistry" },
  { symbol: "K_sp(Mg(OH)₂)", name: "Solubility product (Mg(OH)₂)", value: 1.8e-11, unit: "", category: "chemistry" },

  // === Chemistry — Miscellaneous ===
  { symbol: "ρ_H₂SO₄", name: "Density of conc. H₂SO₄", value: 1830, unit: "kg/m³", category: "chemistry" },
  { symbol: "ρ_HCl", name: "Density of conc. HCl", value: 1190, unit: "kg/m³", category: "chemistry" },
  { symbol: "ρ_HNO₃", name: "Density of conc. HNO₃", value: 1510, unit: "kg/m³", category: "chemistry" },
  { symbol: "ρ_NaOH", name: "Density of NaOH solution", value: 1520, unit: "kg/m³", category: "chemistry" },
  { symbol: "ρ_ethanol", name: "Density of ethanol", value: 789, unit: "kg/m³", category: "chemistry" },
  { symbol: "T_b_water", name: "Boiling point of water", value: 373.15, unit: "K", category: "chemistry" },
  { symbol: "T_m_ice", name: "Melting point of ice", value: 273.15, unit: "K", category: "chemistry" },
  { symbol: "T_b_ethanol", name: "Boiling point of ethanol", value: 351.44, unit: "K", category: "chemistry" },
  { symbol: "T_b_Hg", name: "Boiling point of mercury", value: 629.88, unit: "K", category: "chemistry" },
  { symbol: "ΔH_fus(H₂O)", name: "Enthalpy of fusion (water)", value: 6.01, unit: "kJ/mol", category: "chemistry" },
  { symbol: "ΔH_vap(H₂O)", name: "Enthalpy of vaporization (water)", value: 40.66, unit: "kJ/mol", category: "chemistry" },
  { symbol: "ΔH_f(H₂O)", name: "Enthalpy of formation (water, l)", value: -285.83, unit: "kJ/mol", category: "chemistry" },
  { symbol: "ΔH_f(CO₂)", name: "Enthalpy of formation (CO₂)", value: -393.5, unit: "kJ/mol", category: "chemistry" },
  { symbol: "ΔH_f(NH₃)", name: "Enthalpy of formation (NH₃)", value: -46.11, unit: "kJ/mol", category: "chemistry" },
  { symbol: "ΔH_f(HCl)", name: "Enthalpy of formation (HCl)", value: -92.3, unit: "kJ/mol", category: "chemistry" },
  { symbol: "ΔH_neut", name: "Enthalpy of neutralization (strong acid-base)", value: -57.3, unit: "kJ/mol", category: "chemistry" },
  { symbol: "E°(Zn²⁺/Zn)", name: "Standard electrode potential (Zn)", value: -0.76, unit: "V", category: "chemistry" },
  { symbol: "E°(Cu²⁺/Cu)", name: "Standard electrode potential (Cu)", value: 0.34, unit: "V", category: "chemistry" },
  { symbol: "E°(Ag⁺/Ag)", name: "Standard electrode potential (Ag)", value: 0.80, unit: "V", category: "chemistry" },
  { symbol: "E°(Fe²⁺/Fe)", name: "Standard electrode potential (Fe)", value: -0.44, unit: "V", category: "chemistry" },
  { symbol: "E°(Fe³⁺/Fe²⁺)", name: "Standard electrode potential (Fe³⁺/Fe²⁺)", value: 0.77, unit: "V", category: "chemistry" },
  { symbol: "E°(H⁺/H₂)", name: "Standard electrode potential (SHE)", value: 0.0, unit: "V", category: "chemistry" },
  { symbol: "E°(Cl₂/Cl⁻)", name: "Standard electrode potential (Cl₂)", value: 1.36, unit: "V", category: "chemistry" },
  { symbol: "E°(F₂/F⁻)", name: "Standard electrode potential (F₂)", value: 2.87, unit: "V", category: "chemistry" },
  { symbol: "E°(Na⁺/Na)", name: "Standard electrode potential (Na)", value: -2.71, unit: "V", category: "chemistry" },
  { symbol: "E°(K⁺/K)", name: "Standard electrode potential (K)", value: -2.93, unit: "V", category: "chemistry" },
  { symbol: "E°(Ca²⁺/Ca)", name: "Standard electrode potential (Ca)", value: -2.87, unit: "V", category: "chemistry" },
  { symbol: "E°(Mg²⁺/Mg)", name: "Standard electrode potential (Mg)", value: -2.37, unit: "V", category: "chemistry" },
  { symbol: "E°(Al³⁺/Al)", name: "Standard electrode potential (Al)", value: -1.66, unit: "V", category: "chemistry" },
  { symbol: "E°(Ni²⁺/Ni)", name: "Standard electrode potential (Ni)", value: -0.25, unit: "V", category: "chemistry" },

  // === Astronomy ===
  { symbol: "AU", name: "Astronomical unit", value: 1.495978707e11, unit: "m", category: "astronomy" },
  { symbol: "ly", name: "Light year", value: 9.4607304725808e15, unit: "m", category: "astronomy" },
  { symbol: "pc", name: "Parsec", value: 3.0856775814913673e16, unit: "m", category: "astronomy" },
  { symbol: "M_☉", name: "Solar mass", value: 1.989e30, unit: "kg", category: "astronomy" },
  { symbol: "R_☉", name: "Solar radius", value: 6.957e8, unit: "m", category: "astronomy" },
  { symbol: "L_☉", name: "Solar luminosity", value: 3.828e26, unit: "W", category: "astronomy" },
  { symbol: "T_☉", name: "Solar surface temperature", value: 5778, unit: "K", category: "astronomy" },
  { symbol: "M_⊕", name: "Earth mass", value: 5.9722e24, unit: "kg", category: "astronomy" },
  { symbol: "R_⊕", name: "Earth radius (equatorial)", value: 6.3781e6, unit: "m", category: "astronomy" },
  { symbol: "M_☽", name: "Moon mass", value: 7.342e22, unit: "kg", category: "astronomy" },
  { symbol: "R_☽", name: "Moon radius", value: 1.7374e6, unit: "m", category: "astronomy" },
  { symbol: "d_EM", name: "Earth-Moon distance", value: 3.844e8, unit: "m", category: "astronomy" },
  { symbol: "d_ES", name: "Earth-Sun distance (1 AU)", value: 1.496e11, unit: "m", category: "astronomy" },
  { symbol: "H₀", name: "Hubble constant", value: 67.4, unit: "km/s/Mpc", category: "astronomy" },
  { symbol: "ρ_c", name: "Critical density of universe", value: 8.5e-27, unit: "kg/m³", category: "astronomy" },
  { symbol: "T_CMB", name: "CMB temperature", value: 2.725, unit: "K", category: "astronomy" },
  { symbol: "M♃", name: "Mass of Jupiter", value: 1.898e27, unit: "kg", category: "astronomy" },
  { symbol: "R♃", name: "Radius of Jupiter", value: 6.9911e7, unit: "m", category: "astronomy" },
  { symbol: "M♂", name: "Mass of Mars", value: 6.417e23, unit: "kg", category: "astronomy" },
  { symbol: "R♂", name: "Radius of Mars", value: 3.3895e6, unit: "m", category: "astronomy" },
  { symbol: "M♀", name: "Mass of Venus", value: 4.867e24, unit: "kg", category: "astronomy" },
  { symbol: "R♀", name: "Radius of Venus", value: 6.0518e6, unit: "m", category: "astronomy" },
  { symbol: "M♄", name: "Mass of Saturn", value: 5.683e26, unit: "kg", category: "astronomy" },
  { symbol: "R♄", name: "Radius of Saturn", value: 5.8232e7, unit: "m", category: "astronomy" },

  // === Physics — Elastic Properties ===
  { symbol: "Y_steel", name: "Young's modulus (steel)", value: 2.0e11, unit: "Pa", category: "physics" },
  { symbol: "Y_copper", name: "Young's modulus (copper)", value: 1.1e11, unit: "Pa", category: "physics" },
  { symbol: "Y_aluminium", name: "Young's modulus (aluminium)", value: 7.0e10, unit: "Pa", category: "physics" },
  { symbol: "Y_brass", name: "Young's modulus (brass)", value: 9.0e10, unit: "Pa", category: "physics" },
  { symbol: "Y_iron", name: "Young's modulus (iron)", value: 1.9e11, unit: "Pa", category: "physics" },
  { symbol: "Y_gold", name: "Young's modulus (gold)", value: 7.8e10, unit: "Pa", category: "physics" },
  { symbol: "Y_glass", name: "Young's modulus (glass)", value: 7.0e10, unit: "Pa", category: "physics" },
  { symbol: "Y_concrete", name: "Young's modulus (concrete)", value: 3.0e10, unit: "Pa", category: "physics" },
  { symbol: "Y_wood", name: "Young's modulus (wood)", value: 1.0e10, unit: "Pa", category: "physics" },
  { symbol: "B_water", name: "Bulk modulus (water)", value: 2.2e9, unit: "Pa", category: "physics" },
  { symbol: "B_steel", name: "Bulk modulus (steel)", value: 1.6e11, unit: "Pa", category: "physics" },
  { symbol: "B_copper", name: "Bulk modulus (copper)", value: 1.4e11, unit: "Pa", category: "physics" },
  { symbol: "B_aluminium", name: "Bulk modulus (aluminium)", value: 7.0e10, unit: "Pa", category: "physics" },
  { symbol: "B_glass", name: "Bulk modulus (glass)", value: 3.7e10, unit: "Pa", category: "physics" },
  { symbol: "G_steel", name: "Shear modulus (steel)", value: 8.0e10, unit: "Pa", category: "physics" },
  { symbol: "G_copper", name: "Shear modulus (copper)", value: 4.2e10, unit: "Pa", category: "physics" },
  { symbol: "G_aluminium", name: "Shear modulus (aluminium)", value: 2.6e10, unit: "Pa", category: "physics" },
  { symbol: "G_brass", name: "Shear modulus (brass)", value: 3.5e10, unit: "Pa", category: "physics" },
  { symbol: "G_glass", name: "Shear modulus (glass)", value: 2.5e10, unit: "Pa", category: "physics" },
  { symbol: "σ_steel", name: "Poisson's ratio (steel)", value: 0.29, unit: "", category: "physics" },
  { symbol: "σ_copper", name: "Poisson's ratio (copper)", value: 0.34, unit: "", category: "physics" },
  { symbol: "σ_aluminium", name: "Poisson's ratio (aluminium)", value: 0.33, unit: "", category: "physics" },
  { symbol: "σ_rubber", name: "Poisson's ratio (rubber)", value: 0.50, unit: "", category: "physics" },

  // === Physics — Friction ===
  { symbol: "μ_s_wood", name: "Static friction (wood on wood)", value: 0.5, unit: "", category: "physics" },
  { symbol: "μ_s_steel", name: "Static friction (steel on steel)", value: 0.74, unit: "", category: "physics" },
  { symbol: "μ_s_glass", name: "Static friction (glass on glass)", value: 0.94, unit: "", category: "physics" },
  { symbol: "μ_s_ice", name: "Static friction (ice on ice)", value: 0.1, unit: "", category: "physics" },
  { symbol: "μ_s_rubber", name: "Static friction (rubber on concrete)", value: 1.0, unit: "", category: "physics" },
  { symbol: "μ_k_wood", name: "Kinetic friction (wood on wood)", value: 0.3, unit: "", category: "physics" },
  { symbol: "μ_k_steel", name: "Kinetic friction (steel on steel)", value: 0.57, unit: "", category: "physics" },
  { symbol: "μ_k_ice", name: "Kinetic friction (ice on ice)", value: 0.03, unit: "", category: "physics" },

  // === Physics — Thermal ===
  { symbol: "κ_Cu", name: "Thermal conductivity (copper)", value: 401, unit: "W/(m·K)", category: "physics" },
  { symbol: "κ_Al", name: "Thermal conductivity (aluminium)", value: 237, unit: "W/(m·K)", category: "physics" },
  { symbol: "κ_Fe", name: "Thermal conductivity (iron)", value: 80, unit: "W/(m·K)", category: "physics" },
  { symbol: "κ_Ag", name: "Thermal conductivity (silver)", value: 429, unit: "W/(m·K)", category: "physics" },
  { symbol: "κ_Au", name: "Thermal conductivity (gold)", value: 318, unit: "W/(m·K)", category: "physics" },
  { symbol: "κ_glass", name: "Thermal conductivity (glass)", value: 1.0, unit: "W/(m·K)", category: "physics" },
  { symbol: "κ_water", name: "Thermal conductivity (water)", value: 0.6, unit: "W/(m·K)", category: "physics" },
  { symbol: "κ_air", name: "Thermal conductivity (air)", value: 0.026, unit: "W/(m·K)", category: "physics" },
  { symbol: "κ_wood", name: "Thermal conductivity (wood)", value: 0.13, unit: "W/(m·K)", category: "physics" },
  { symbol: "α_Fe", name: "Coeff. of linear expansion (iron)", value: 12e-6, unit: "/K", category: "physics" },
  { symbol: "α_Cu", name: "Coeff. of linear expansion (copper)", value: 17e-6, unit: "/K", category: "physics" },
  { symbol: "α_Al", name: "Coeff. of linear expansion (aluminium)", value: 23e-6, unit: "/K", category: "physics" },
  { symbol: "α_steel", name: "Coeff. of linear expansion (steel)", value: 11e-6, unit: "/K", category: "physics" },
  { symbol: "α_glass", name: "Coeff. of linear expansion (glass)", value: 9e-6, unit: "/K", category: "physics" },
  { symbol: "α_brass", name: "Coeff. of linear expansion (brass)", value: 19e-6, unit: "/K", category: "physics" },
  { symbol: "β_water", name: "Coeff. of volume expansion (water)", value: 207e-6, unit: "/K", category: "physics" },
  { symbol: "β_Hg", name: "Coeff. of volume expansion (mercury)", value: 181e-6, unit: "/K", category: "physics" },
  { symbol: "β_air", name: "Coeff. of volume expansion (air)", value: 3.67e-3, unit: "/K", category: "physics" },

  // === Physics — Electrical ===
  { symbol: "ρ_Cu", name: "Resistivity (copper, 20°C)", value: 1.68e-8, unit: "Ω·m", category: "physics" },
  { symbol: "ρ_Al", name: "Resistivity (aluminium, 20°C)", value: 2.82e-8, unit: "Ω·m", category: "physics" },
  { symbol: "ρ_Fe", name: "Resistivity (iron, 20°C)", value: 9.71e-8, unit: "Ω·m", category: "physics" },
  { symbol: "ρ_Ag", name: "Resistivity (silver, 20°C)", value: 1.59e-8, unit: "Ω·m", category: "physics" },
  { symbol: "ρ_Au", name: "Resistivity (gold, 20°C)", value: 2.44e-8, unit: "Ω·m", category: "physics" },
  { symbol: "ρ_W", name: "Resistivity (tungsten, 20°C)", value: 5.6e-8, unit: "Ω·m", category: "physics" },
  { symbol: "ρ_Nichrome", name: "Resistivity (nichrome, 20°C)", value: 1.10e-6, unit: "Ω·m", category: "physics" },
  { symbol: "ρ_C", name: "Resistivity (carbon, 20°C)", value: 3.5e-5, unit: "Ω·m", category: "physics" },
  { symbol: "ρ_Hg_elec", name: "Resistivity (mercury, 20°C)", value: 9.8e-7, unit: "Ω·m", category: "physics" },
  { symbol: "σ_Cu", name: "Conductivity (copper)", value: 5.96e7, unit: "S/m", category: "physics" },
  { symbol: "σ_Ag", name: "Conductivity (silver)", value: 6.30e7, unit: "S/m", category: "physics" },
  { symbol: "α_R_Cu", name: "Temp coeff of resistance (copper)", value: 3.9e-3, unit: "/K", category: "physics" },
  { symbol: "μ_e_Cu", name: "Mobility (electrons in copper)", value: 0.0044, unit: "m²/(V·s)", category: "physics" },
  { symbol: "μ_e_Si", name: "Mobility (electrons in silicon)", value: 0.14, unit: "m²/(V·s)", category: "physics" },
  { symbol: "μ_h_Si", name: "Mobility (holes in silicon)", value: 0.05, unit: "m²/(V·s)", category: "physics" },

  // === Physics — Dielectric Constants (Relative Permittivity) ===
  { symbol: "κ_water", name: "Dielectric constant (water)", value: 80, unit: "", category: "physics" },
  { symbol: "κ_glass", name: "Dielectric constant (glass)", value: 5, unit: "", category: "physics" },
  { symbol: "κ_mica", name: "Dielectric constant (mica)", value: 6, unit: "", category: "physics" },
  { symbol: "κ_paper", name: "Dielectric constant (paper)", value: 3.7, unit: "", category: "physics" },
  { symbol: "κ_air", name: "Dielectric constant (air)", value: 1.0006, unit: "", category: "physics" },
  { symbol: "κ_vacuum", name: "Dielectric constant (vacuum)", value: 1.0, unit: "", category: "physics" },
  { symbol: "κ_ethanol", name: "Dielectric constant (ethanol)", value: 24, unit: "", category: "physics" },
  { symbol: "κ_glycerin", name: "Dielectric constant (glycerin)", value: 42, unit: "", category: "physics" },

  // === Physics — Magnetic ===
  { symbol: "μ_e", name: "Electron magnetic moment", value: -9.2847647043e-24, unit: "J/T", category: "physics" },
  { symbol: "μ_p", name: "Proton magnetic moment", value: 1.410606797e-26, unit: "J/T", category: "physics" },
  { symbol: "μ_n", name: "Neutron magnetic moment", value: -9.662365e-27, unit: "J/T", category: "physics" },
  { symbol: "g_e", name: "Electron g-factor", value: 2.002319304, unit: "", category: "physics" },
  { symbol: "g_p", name: "Proton g-factor", value: 5.5857, unit: "", category: "physics" },
  { symbol: "K_J", name: "Josephson constant", value: 4.835978484e14, unit: "Hz/V", category: "physics" },
  { symbol: "R_K", name: "von Klitzing constant", value: 25812.807, unit: "Ω", category: "physics" },
  { symbol: "G₀", name: "Conductance quantum", value: 7.748091729e-5, unit: "S", category: "physics" },

  // === Physics — Particle (extended) ===
  { symbol: "m_d", name: "Deuteron mass", value: 3.343583719e-27, unit: "kg", category: "physics" },
  { symbol: "m_t", name: "Triton mass", value: 5.007356744e-27, unit: "kg", category: "physics" },
  { symbol: "m_helion", name: "Helion mass", value: 5.006412e-27, unit: "kg", category: "physics" },
  { symbol: "m_π±", name: "Charged pion mass", value: 2.488e-28, unit: "kg", category: "physics" },
  { symbol: "m_π⁰", name: "Neutral pion mass", value: 2.406e-28, unit: "kg", category: "physics" },
  { symbol: "m_K", name: "Kaon mass", value: 8.800e-28, unit: "kg", category: "physics" },
  { symbol: "W", name: "W boson mass", value: 1.4349e-25, unit: "kg", category: "physics" },
  { symbol: "Z", name: "Z boson mass", value: 1.6266e-25, unit: "kg", category: "physics" },
  { symbol: "m_Higgs", name: "Higgs boson mass", value: 2.226e-25, unit: "kg", category: "physics" },
  { symbol: "m_d(quark)", name: "Down quark mass", value: 7.5e-30, unit: "kg", category: "physics" },
  { symbol: "m_u(quark)", name: "Up quark mass", value: 4.2e-30, unit: "kg", category: "physics" },
  { symbol: "m_s(quark)", name: "Strange quark mass", value: 1.67e-28, unit: "kg", category: "physics" },
  { symbol: "m_c(quark)", name: "Charm quark mass", value: 2.09e-27, unit: "kg", category: "physics" },
  { symbol: "m_b(quark)", name: "Bottom quark mass", value: 7.06e-27, unit: "kg", category: "physics" },
  { symbol: "m_t(quark)", name: "Top quark mass", value: 3.08e-25, unit: "kg", category: "physics" },

  // === Physics — Work Functions & Ionization ===
  { symbol: "Φ_Na", name: "Work function (sodium)", value: 2.3, unit: "eV", category: "physics" },
  { symbol: "Φ_K", name: "Work function (potassium)", value: 2.25, unit: "eV", category: "physics" },
  { symbol: "Φ_Cs", name: "Work function (caesium)", value: 2.14, unit: "eV", category: "physics" },
  { symbol: "Φ_Ca", name: "Work function (calcium)", value: 2.87, unit: "eV", category: "physics" },
  { symbol: "Φ_Cu", name: "Work function (copper)", value: 4.65, unit: "eV", category: "physics" },
  { symbol: "Φ_Zn", name: "Work function (zinc)", value: 4.31, unit: "eV", category: "physics" },
  { symbol: "Φ_Ag", name: "Work function (silver)", value: 4.26, unit: "eV", category: "physics" },
  { symbol: "Φ_Al", name: "Work function (aluminium)", value: 4.28, unit: "eV", category: "physics" },
  { symbol: "Φ_W", name: "Work function (tungsten)", value: 4.55, unit: "eV", category: "physics" },
  { symbol: "Φ_Fe", name: "Work function (iron)", value: 4.5, unit: "eV", category: "physics" },
  { symbol: "E_ion_H", name: "Ionization energy (hydrogen)", value: 13.6, unit: "eV", category: "physics" },
  { symbol: "E_ion_He", name: "Ionization energy (helium)", value: 24.6, unit: "eV", category: "physics" },
  { symbol: "E_ion_Na", name: "Ionization energy (sodium)", value: 5.14, unit: "eV", category: "physics" },
  { symbol: "r_nucleus", name: "Nuclear radius constant (r₀)", value: 1.2, unit: "fm", category: "physics" },

  // === Chemistry — Extended ===
  { symbol: "amu", name: "1 Atomic mass unit (1 u)", value: 1.66053906660e-27, unit: "kg", category: "chemistry" },
  { symbol: "1 u", name: "1 Atomic mass unit (1 u)", value: 1.66053906660e-27, unit: "kg", category: "chemistry" },
  { symbol: "1 amu", name: "1 Atomic mass unit (1 amu)", value: 1.66053906660e-27, unit: "kg", category: "chemistry" },
  { symbol: "u(MeV/c²)", name: "1 u in MeV/c²", value: 931.494, unit: "MeV/c²", category: "chemistry" },
  { symbol: "K_a(H₂SO₄)", name: "Dissociation const. (sulfuric acid, Ka1)", value: 1.0e3, unit: "", category: "chemistry" },
  { symbol: "K_a(H₃BO₃)", name: "Dissociation const. (boric acid)", value: 5.8e-10, unit: "", category: "chemistry" },
  { symbol: "K_a(HCOOH)", name: "Dissociation const. (formic acid)", value: 1.8e-4, unit: "", category: "chemistry" },
  { symbol: "K_a(C₆H₅OH)", name: "Dissociation const. (phenol)", value: 1.0e-10, unit: "", category: "chemistry" },
  { symbol: "K_sp(PbCl₂)", name: "Solubility product (PbCl₂)", value: 1.6e-5, unit: "", category: "chemistry" },
  { symbol: "K_sp(AgBr)", name: "Solubility product (AgBr)", value: 5.0e-13, unit: "", category: "chemistry" },
  { symbol: "K_sp(AgI)", name: "Solubility product (AgI)", value: 8.3e-17, unit: "", category: "chemistry" },
  { symbol: "K_sp(CaSO₄)", name: "Solubility product (CaSO₄)", value: 2.4e-5, unit: "", category: "chemistry" },
  { symbol: "K_sp(SrSO₄)", name: "Solubility product (SrSO₄)", value: 3.2e-7, unit: "", category: "chemistry" },
  { symbol: "K_sp(PbI₂)", name: "Solubility product (PbI₂)", value: 7.1e-9, unit: "", category: "chemistry" },
  { symbol: "K_sp(MgCO₃)", name: "Solubility product (MgCO₃)", value: 3.5e-8, unit: "", category: "chemistry" },
  { symbol: "K_sp(ZnS)", name: "Solubility product (ZnS)", value: 1.6e-24, unit: "", category: "chemistry" },
  { symbol: "K_sp(CuS)", name: "Solubility product (CuS)", value: 6.3e-36, unit: "", category: "chemistry" },
  { symbol: "E°(Mn²⁺/Mn)", name: "Standard electrode potential (Mn)", value: -1.18, unit: "V", category: "chemistry" },
  { symbol: "E°(Cr³⁺/Cr)", name: "Standard electrode potential (Cr)", value: -0.74, unit: "V", category: "chemistry" },
  { symbol: "E°(Co²⁺/Co)", name: "Standard electrode potential (Co)", value: -0.28, unit: "V", category: "chemistry" },
  { symbol: "E°(Sn²⁺/Sn)", name: "Standard electrode potential (Sn)", value: -0.14, unit: "V", category: "chemistry" },
  { symbol: "E°(Pb²⁺/Pb)", name: "Standard electrode potential (Pb)", value: -0.13, unit: "V", category: "chemistry" },
  { symbol: "E°(Hg²⁺/Hg)", name: "Standard electrode potential (Hg)", value: 0.85, unit: "V", category: "chemistry" },
  { symbol: "E°(Au³⁺/Au)", name: "Standard electrode potential (Au)", value: 1.50, unit: "V", category: "chemistry" },
  { symbol: "E°(Br₂/Br⁻)", name: "Standard electrode potential (Br₂)", value: 1.07, unit: "V", category: "chemistry" },
  { symbol: "E°(I₂/I⁻)", name: "Standard electrode potential (I₂)", value: 0.54, unit: "V", category: "chemistry" },
  { symbol: "E°(MnO₄⁻/Mn²⁺)", name: "Standard electrode potential (MnO₄⁻)", value: 1.51, unit: "V", category: "chemistry" },
  { symbol: "E°(Cr₂O₇²⁻/Cr³⁺)", name: "Standard electrode potential (Cr₂O₇²⁻)", value: 1.33, unit: "V", category: "chemistry" },
  { symbol: "χ_F", name: "Electronegativity (Fluorine)", value: 4.0, unit: "", category: "chemistry" },
  { symbol: "χ_O", name: "Electronegativity (Oxygen)", value: 3.5, unit: "", category: "chemistry" },
  { symbol: "χ_Cl", name: "Electronegativity (Chlorine)", value: 3.0, unit: "", category: "chemistry" },
  { symbol: "χ_N", name: "Electronegativity (Nitrogen)", value: 3.0, unit: "", category: "chemistry" },
  { symbol: "χ_H", name: "Electronegativity (Hydrogen)", value: 2.1, unit: "", category: "chemistry" },
  { symbol: "χ_C", name: "Electronegativity (Carbon)", value: 2.5, unit: "", category: "chemistry" },
  { symbol: "χ_Na", name: "Electronegativity (Sodium)", value: 0.9, unit: "", category: "chemistry" },
  { symbol: "χ_K", name: "Electronegativity (Potassium)", value: 0.8, unit: "", category: "chemistry" },
  { symbol: "EA_Cl", name: "Electron affinity (Chlorine)", value: 3.6, unit: "eV", category: "chemistry" },
  { symbol: "EA_F", name: "Electron affinity (Fluorine)", value: 3.4, unit: "eV", category: "chemistry" },
  { symbol: "EA_O", name: "Electron affinity (Oxygen)", value: 1.5, unit: "eV", category: "chemistry" },
  { symbol: "EA_H", name: "Electron affinity (Hydrogen)", value: 0.8, unit: "eV", category: "chemistry" },
  { symbol: "ΔH_sub(CO₂)", name: "Enthalpy of sublimation (CO₂)", value: 25.2, unit: "kJ/mol", category: "chemistry" },
  { symbol: "ΔH_comb(CH₄)", name: "Enthalpy of combustion (methane)", value: -890.4, unit: "kJ/mol", category: "chemistry" },
  { symbol: "ΔH_comb(C₂H₅OH)", name: "Enthalpy of combustion (ethanol)", value: -1367, unit: "kJ/mol", category: "chemistry" },
  { symbol: "ΔH_comb(C₆H₁₂O₆)", name: "Enthalpy of combustion (glucose)", value: -2808, unit: "kJ/mol", category: "chemistry" },
  { symbol: "ΔH_comb(C)", name: "Enthalpy of combustion (carbon)", value: -393.5, unit: "kJ/mol", category: "chemistry" },
  { symbol: "ΔH_comb(H₂)", name: "Enthalpy of combustion (hydrogen)", value: -285.83, unit: "kJ/mol", category: "chemistry" },
  { symbol: "S°(H₂O)", name: "Standard entropy (water, l)", value: 69.9, unit: "J/(mol·K)", category: "chemistry" },
  { symbol: "S°(H₂)", name: "Standard entropy (hydrogen gas)", value: 130.7, unit: "J/(mol·K)", category: "chemistry" },
  { symbol: "S°(O₂)", name: "Standard entropy (oxygen gas)", value: 205.1, unit: "J/(mol·K)", category: "chemistry" },
  { symbol: "S°(N₂)", name: "Standard entropy (nitrogen gas)", value: 191.6, unit: "J/(mol·K)", category: "chemistry" },
  { symbol: "S°(CO₂)", name: "Standard entropy (carbon dioxide)", value: 213.7, unit: "J/(mol·K)", category: "chemistry" },
  { symbol: "ΔG_f(H₂O)", name: "Gibbs free energy of formation (water)", value: -237.1, unit: "kJ/mol", category: "chemistry" },
  { symbol: "ΔG_f(CO₂)", name: "Gibbs free energy of formation (CO₂)", value: -394.4, unit: "kJ/mol", category: "chemistry" },
  { symbol: "ΔG_f(NH₃)", name: "Gibbs free energy of formation (NH₃)", value: -16.4, unit: "kJ/mol", category: "chemistry" },
];

export interface UnitCategory {
  name: string;
  baseUnit: string;
  units: { symbol: string; name: string; toBase: number }[];
}

export const UNIT_CATEGORIES: UnitCategory[] = [
  {
    name: "Length",
    baseUnit: "m",
    units: [
      { symbol: "nm", name: "Nanometer", toBase: 1e-9 },
      { symbol: "μm", name: "Micrometer", toBase: 1e-6 },
      { symbol: "mm", name: "Millimeter", toBase: 1e-3 },
      { symbol: "cm", name: "Centimeter", toBase: 1e-2 },
      { symbol: "m", name: "Meter", toBase: 1 },
      { symbol: "km", name: "Kilometer", toBase: 1e3 },
      { symbol: "in", name: "Inch", toBase: 0.0254 },
      { symbol: "ft", name: "Foot", toBase: 0.3048 },
      { symbol: "yd", name: "Yard", toBase: 0.9144 },
      { symbol: "mi", name: "Mile", toBase: 1609.344 },
      { symbol: "nmi", name: "Nautical mile", toBase: 1852 },
    ],
  },
  {
    name: "Area",
    baseUnit: "m²",
    units: [
      { symbol: "mm²", name: "Square millimeter", toBase: 1e-6 },
      { symbol: "cm²", name: "Square centimeter", toBase: 1e-4 },
      { symbol: "m²", name: "Square meter", toBase: 1 },
      { symbol: "ha", name: "Hectare", toBase: 1e4 },
      { symbol: "km²", name: "Square kilometer", toBase: 1e6 },
      { symbol: "in²", name: "Square inch", toBase: 0.00064516 },
      { symbol: "ft²", name: "Square foot", toBase: 0.092903 },
      { symbol: "ac", name: "Acre", toBase: 4046.86 },
    ],
  },
  {
    name: "Volume",
    baseUnit: "m³",
    units: [
      { symbol: "mL", name: "Milliliter", toBase: 1e-6 },
      { symbol: "L", name: "Liter", toBase: 1e-3 },
      { symbol: "m³", name: "Cubic meter", toBase: 1 },
      { symbol: "cm³", name: "Cubic centimeter", toBase: 1e-6 },
      { symbol: "gal", name: "US gallon", toBase: 0.00378541 },
      { symbol: "qt", name: "US quart", toBase: 0.000946353 },
      { symbol: "pt", name: "US pint", toBase: 0.000473176 },
      { symbol: "fl oz", name: "US fluid ounce", toBase: 2.95735e-5 },
    ],
  },
  {
    name: "Mass",
    baseUnit: "kg",
    units: [
      { symbol: "mg", name: "Milligram", toBase: 1e-6 },
      { symbol: "g", name: "Gram", toBase: 1e-3 },
      { symbol: "kg", name: "Kilogram", toBase: 1 },
      { symbol: "t", name: "Metric ton", toBase: 1e3 },
      { symbol: "oz", name: "Ounce", toBase: 0.0283495 },
      { symbol: "lb", name: "Pound", toBase: 0.453592 },
      { symbol: "u", name: "Unified atomic mass", toBase: 1.66053907e-27 },
    ],
  },
  {
    name: "Time",
    baseUnit: "s",
    units: [
      { symbol: "ns", name: "Nanosecond", toBase: 1e-9 },
      { symbol: "μs", name: "Microsecond", toBase: 1e-6 },
      { symbol: "ms", name: "Millisecond", toBase: 1e-3 },
      { symbol: "s", name: "Second", toBase: 1 },
      { symbol: "min", name: "Minute", toBase: 60 },
      { symbol: "h", name: "Hour", toBase: 3600 },
      { symbol: "d", name: "Day", toBase: 86400 },
      { symbol: "wk", name: "Week", toBase: 604800 },
      { symbol: "yr", name: "Year (365d)", toBase: 31557600 },
    ],
  },
  {
    name: "Temperature",
    baseUnit: "K",
    units: [
      { symbol: "K", name: "Kelvin", toBase: 1 },
      { symbol: "°C", name: "Celsius", toBase: 1 },
      { symbol: "°F", name: "Fahrenheit", toBase: 1 },
      { symbol: "°R", name: "Rankine", toBase: 1 },
    ],
  },
  {
    name: "Speed",
    baseUnit: "m/s",
    units: [
      { symbol: "m/s", name: "Meters per second", toBase: 1 },
      { symbol: "km/h", name: "Kilometers per hour", toBase: 1 / 3.6 },
      { symbol: "mph", name: "Miles per hour", toBase: 0.44704 },
      { symbol: "ft/s", name: "Feet per second", toBase: 0.3048 },
      { symbol: "kn", name: "Knot", toBase: 0.514444 },
      { symbol: "c", name: "Speed of light", toBase: 299792458 },
    ],
  },
  {
    name: "Energy",
    baseUnit: "J",
    units: [
      { symbol: "J", name: "Joule", toBase: 1 },
      { symbol: "kJ", name: "Kilojoule", toBase: 1e3 },
      { symbol: "cal", name: "Calorie", toBase: 4.184 },
      { symbol: "kcal", name: "Kilocalorie", toBase: 4184 },
      { symbol: "Wh", name: "Watt-hour", toBase: 3600 },
      { symbol: "kWh", name: "Kilowatt-hour", toBase: 3.6e6 },
      { symbol: "eV", name: "Electron volt", toBase: 1.602176634e-19 },
      { symbol: "BTU", name: "British thermal unit", toBase: 1055.06 },
    ],
  },
  {
    name: "Pressure",
    baseUnit: "Pa",
    units: [
      { symbol: "Pa", name: "Pascal", toBase: 1 },
      { symbol: "kPa", name: "Kilopascal", toBase: 1e3 },
      { symbol: "MPa", name: "Megapascal", toBase: 1e6 },
      { symbol: "bar", name: "Bar", toBase: 1e5 },
      { symbol: "atm", name: "Atmosphere", toBase: 101325 },
      { symbol: "mmHg", name: "Millimeter of mercury", toBase: 133.322 },
      { symbol: "psi", name: "Pound per square inch", toBase: 6894.76 },
    ],
  },
];

/** Convert temperature between units (non-linear, handled specially). */
export function convertTemperature(value: number, from: string, to: string): number {
  let kelvin: number;
  switch (from) {
    case "K": kelvin = value; break;
    case "°C": kelvin = value + 273.15; break;
    case "°F": kelvin = (value - 32) * (5 / 9) + 273.15; break;
    case "°R": kelvin = value * (5 / 9); break;
    default: kelvin = value;
  }
  switch (to) {
    case "K": return kelvin;
    case "°C": return kelvin - 273.15;
    case "°F": return (kelvin - 273.15) * (9 / 5) + 32;
    case "°R": return kelvin * (9 / 5);
    default: return kelvin;
  }
}

/** Convert a value from one unit to another within a category. */
export function convertUnit(
  value: number,
  fromSymbol: string,
  toSymbol: string,
  categoryName: string,
): number {
  const cat = UNIT_CATEGORIES.find((c) => c.name === categoryName);
  if (!cat) return NaN;
  if (cat.name === "Temperature") {
    return convertTemperature(value, fromSymbol, toSymbol);
  }
  const from = cat.units.find((u) => u.symbol === fromSymbol);
  const to = cat.units.find((u) => u.symbol === toSymbol);
  if (!from || !to) return NaN;
  // value_in_base = value * from.toBase ; result = value_in_base / to.toBase
  return (value * from.toBase) / to.toBase;
}
